/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_Light_Status_STUB_DEFAULT_HPP_
#define V1_COMMONAPI_Light_Status_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/commonapi/LightStatusStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace commonapi {

/**
 * Provides a default implementation for LightStatusStubRemoteEvent and
 * LightStatusStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT LightStatusStubDefault
    : public virtual LightStatusStub {
public:
    COMMONAPI_EXPORT LightStatusStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(LightStatus::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT LightStatusStubRemoteEvent* initStubAdapter(const std::shared_ptr< LightStatusStubAdapter> &_adapter) {
        CommonAPI::Stub<LightStatusStubAdapter, LightStatusStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual const bool &getLightAttribute() {
        return lightAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const bool &getLightAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getLightAttribute();
    }
    COMMONAPI_EXPORT virtual void setLightAttribute(bool _value) {
        const bool valueChanged = trySetLightAttribute(std::move(_value));
        if (valueChanged) {
            fireLightAttributeChanged(lightAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void setLightAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, bool _value) {
        (void)_client;
        setLightAttribute(_value);
    }


protected:
    COMMONAPI_EXPORT virtual bool trySetLightAttribute(bool _value) {
        if (!validateLightAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<LightStatusStubAdapter> stubAdapter = CommonAPI::Stub<LightStatusStubAdapter, LightStatusStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockLightAttribute(true);
            valueChanged = (lightAttributeValue_ != _value);
            lightAttributeValue_ = std::move(_value);
            stubAdapter->lockLightAttribute(false);
        } else {
            valueChanged = (lightAttributeValue_ != _value);
            lightAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateLightAttributeRequestedValue(const bool &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual void onRemoteLightAttributeChanged() {
        // No operation in default
    }
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual LightStatusStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(LightStatusStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }

        COMMONAPI_EXPORT virtual void onRemoteLightAttributeChanged() {
            assert(defaultStub_ !=NULL);
            defaultStub_->onRemoteLightAttributeChanged();
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetLightAttribute(bool _value) {
            assert(defaultStub_ !=NULL);
            return defaultStub_->trySetLightAttribute(std::move(_value));
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetLightAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, bool _value) {
            (void)_client;
            return onRemoteSetLightAttribute(_value);
        }

    private:
        LightStatusStubDefault *defaultStub_;
    };
protected:
    LightStatusStubDefault::RemoteEventHandler remoteEventHandler_;

private:

    bool lightAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_Light_Status_STUB_DEFAULT
