/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COMMONAPI_LIGHT_STATUS_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COMMONAPI_LIGHT_STATUS_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/commonapi/LightStatusStub.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

template <typename _Stub = ::v1::commonapi::LightStatusStub, typename... _Stubs>
class LightStatusSomeIPStubAdapterInternal
    : public virtual LightStatusStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< LightStatusSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> LightStatusSomeIPStubAdapterHelper;

    ~LightStatusSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        LightStatusSomeIPStubAdapterHelper::deinit();
    }

    void fireLightAttributeChanged(const bool &_value);
    
    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::LightStatusStub,
        CommonAPI::Version
    > getLightStatusInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::LightStatusStub,
        bool
    > getLightAttributeStubDispatcher;
    
    CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
        ::v1::commonapi::LightStatusStub,
        bool
    > setLightAttributeStubDispatcher;
    
    LightStatusSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        LightStatusSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< LightStatusStub>(_stub)),
        getLightStatusInterfaceVersionStubDispatcher(&LightStatusStub::lockInterfaceVersionAttribute, &LightStatusStub::getInterfaceVersion, false, true),
        getLightAttributeStubDispatcher(
            &::v1::commonapi::LightStatusStub::lockLightAttribute,
            &::v1::commonapi::LightStatusStub::getLightAttribute,
            false,
            _stub->hasElement(0)),
        setLightAttributeStubDispatcher(
            &::v1::commonapi::LightStatusStub::lockLightAttribute,
            &::v1::commonapi::LightStatusStub::getLightAttribute,
            &LightStatusStubRemoteEvent::onRemoteSetLightAttribute,
            &LightStatusStubRemoteEvent::onRemoteLightAttributeChanged,
            &LightStatusStubAdapter::fireLightAttributeChanged,
            false,
            _stub->hasElement(0))
    {
        LightStatusSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xc1f) }, &getLightAttributeStubDispatcher );
        LightStatusSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xc20) }, &setLightAttributeStubDispatcher );
        std::shared_ptr<CommonAPI::SomeIP::ClientId> itsClient = std::make_shared<CommonAPI::SomeIP::ClientId>(0xFFFF, 0xFFFFFFFF, 0xFFFFFFFF);

        // Provided events/fields
        if (_stub->hasElement(0)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x84dd)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x84dd), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireLightAttributeChanged(std::dynamic_pointer_cast< ::v1::commonapi::LightStatusStub>(_stub)->getLightAttribute(itsClient));
        }

    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void LightStatusSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireLightAttributeChanged(const bool &_value) {
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            bool
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x84dd),
        false,
        _value
    );
}


template <typename _Stub, typename... _Stubs>
void LightStatusSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void LightStatusSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v1::commonapi::LightStatusStub, typename... _Stubs>
class LightStatusSomeIPStubAdapter
    : public LightStatusSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    LightStatusSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          LightStatusSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_Light_Status_SOMEIP_STUB_ADAPTER_HPP_
