/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/commonapi/LightStatusSomeIPStubAdapter.hpp>
#include <v1/commonapi/LightStatus.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createLightStatusSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< LightStatusSomeIPStubAdapter<::v1::commonapi::LightStatusStub>>(_address, _connection, _stub);
}

void initializeLightStatusSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.LightStatus:v1_0:LightStatus_from_gamepad",
         0x1239, 0x567d, 1, 0);
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.LightStatus:v1_0:LightStatus_from_racer",
         0x1239, 0x567e, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "commonapi.LightStatus:v1_0",
        &createLightStatusSomeIPStubAdapter);
}

INITIALIZER(registerLightStatusSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeLightStatusSomeIPStubAdapter);
}

} // namespace commonapi
} // namespace v1
